spring:
  datasource:
    url: jdbc:mysql://47.96.13.85:3306/test?useSSL=true
    username: test
    password: Test@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /rest
  thymeleaf:
    cache: false
#  mvc:
#    throw-exception-if-no-handler-found: true # 出现错误时, 直接抛出异常
#  resources:
#    add-mappings: false # 不要为我们工程中的资源文件建立映射

# JWT 认证配置
jwt:
  header: Authorization
  secret: s-mk123456
  expiration: 604800 #token七天不过期
  tokenHead: "Bearer "
  exceptUrl: "/auth/**"
